# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  MONGO_HOST: cluster0.mrt5ygm.mongodb.net
  Port: 8000

permissions:
  contents: read

jobs:
  build:      
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python 3.10 and Install Dependencies
      uses: ./.github/actions/install-deps # Starts at root of repository
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python 3.10 and Install Dependencies
      uses: ./.github/actions/install-deps # Starts at root of repository

    - name: Run FastAPI app
      run: |
        uvicorn main:app --host 0.0.0.0 --port $Port --timeout-keep-alive 5 &
        sleep 5
        echo "FastAPI app is running"


  test:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python 3.10 and Install Dependencies
      uses: ./.github/actions/install-deps # Starts at root of repository

    - name: Test with pytest
      id: pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q > pytest-result.txt

    - name: Upload test results
      if: failure() && steps.pytest.outcome != 'success'
      uses: actions/upload-artifact@v4
      with:
        name: pytest-result
        path: pytest-result.txt

